In [10]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the data into a pandas DataFrame
data = pd.read_excel("C:/Users/gulsh/Downloads/ward_landuse.xlsx")
data['WARD_NO'] = data['WARD_NO'].replace({'CANT_1': 501,
    'CANT_2': 502,
    'CANT_3': 503,
    'CANT_4': 504,
    'CANT_5': 505,
    'CANT_6': 506,
    'CANT_7': 507,
    'CANT_8': 508,
    'NDMC_1': 601,
    'NDMC_2': 602,
    'NDMC_3': 603,
    'NDMC_4': 604,
    'NDMC_5': 605,
    'NDMC_6': 606,
    'NDMC_7': 607,
    'NDMC_8': 608,
    'NDMC_9': 609})
data

,OBJECTID,WARD_NO,P_D2020,POP2020,LTYPE,Area,LANDUSEID,Category,Category_1,SHORT_CAT,CATNO,CATCODE
0,1,501,45.25382,5783,LS,0.180035,666,Commercial Area,Commercial Area,COM_AR,3,CAT3
1,1,501,45.25382,5783,LS,0.482429,667,Industrial Area,Industrial Area,I_A,5,CAT5
2,1,501,45.25382,5783,LS,2.537699,659,Industrial Area,Industrial Area,I_A,5,CAT5
3,1,501,45.25382,5783,LS,1.080003,460,Industrial Area,Industrial Area,I_A,5,CAT5
4,1,501,45.25382,5783,LS,37.685429,9,Government Land,Government Land,GOV_LND,4,CAT4
...,...,...,...,...,...,...,...,...,...,...,...,...
2428,253,15,295.34072,51903,LS,3.295735,1055,Residential Area,Residential Area,RES_A,9,CAT9
2429,253,15,295.34072,51903,LS,0.060549,614,Residential Area,Residential Area,RES_A,9,CAT9
2430,253,15,295.34072,51903,LS,0.045417,612,Commercial Area,Commercial Area,COM_AR,3,CAT3
2431,253,15,295.34072,51903,LS,0.662699,610,Industrial Area,Industrial Area,I_A,5,CAT5
2432,253,15,295.34072,51903,LS,0.198218,611,Recreational Area,Recreational Area,REC_A,8,CAT8

In [11]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the data into a pandas DataFrame
data = pd.read_excel("C:/Users/gulsh/Downloads/ward_landuse.xlsx")
data['WARD_NO'] = data['WARD_NO'].replace({'CANT_1': 501,
    'CANT_2': 502,
    'CANT_3': 503,
    'CANT_4': 504,
    'CANT_5': 505,
    'CANT_6': 506,
    'CANT_7': 507,
    'CANT_8': 508,
    'NDMC_1': 601,
    'NDMC_2': 602,
    'NDMC_3': 603,
    'NDMC_4': 604,
    'NDMC_5': 605,
    'NDMC_6': 606,
    'NDMC_7': 607,
    'NDMC_8': 608,
    'NDMC_9': 609})
data.dtypes

OBJECTID        int64
WARD_NO        object
P_D2020       float64
POP2020         int64
LTYPE          object
Area          float64
LANDUSEID       int64
Category       object
Category_1     object
SHORT_CAT      object
CATNO           int64
CATCODE        object
dtype: object

In [15]:
import pandas as pd
data = pd.read_excel("C:/Users/gulsh/Downloads/ward_landuse.xlsx")
data['WARD_NO'] = data['WARD_NO'].replace({'CANT_1': 501,
    'CANT_2': 502,
    'CANT_3': 503,
    'CANT_4': 504,
    'CANT_5': 505,
    'CANT_6': 506,
    'CANT_7': 507,
    'CANT_8': 508,
    'NDMC_1': 601,
    'NDMC_2': 602,
    'NDMC_3': 603,
    'NDMC_4': 604,
    'NDMC_5': 605,
    'NDMC_6': 606,
    'NDMC_7': 607,
    'NDMC_8': 608,
    'NDMC_9': 609})
data['WARD_NO'] = data['WARD_NO'].astype(int)
# Assuming the dataset is stored in a DataFrame called 'data'
filtered_data = data[data['CATNO'] == 9]

ward_area = filtered_data.groupby('WARD_NO')['Area'].sum()
total_area = data.groupby('WARD_NO')['Area'].sum()

percentage_area = (ward_area / total_area) * 100

result = pd.DataFrame({'WARD_NO': percentage_area.index, 'Residential_area_percentage': percentage_area.values})

# Print the result
result.to_excel("C:/Users/gulsh/Downloads/ward_vs_residential_area.xlsx", index=False)

In [23]:
import pandas as pd
data = pd.read_excel("C:/Users/gulsh/Downloads/Ward_LST_16may.xlsx")
data['WARD_NO'] = data['WARD_NO'].replace({'CANT_1': 501,
    'CANT_2': 502,
    'CANT_3': 503,
    'CANT_4': 504,
    'CANT_5': 505,
    'CANT_6': 506,
    'CANT_7': 507,
    'CANT_8': 508,
    'NDMC_1': 601,
    'NDMC_2': 602,
    'NDMC_3': 603,
    'NDMC_4': 604,
    'NDMC_5': 605,
    'NDMC_6': 606,
    'NDMC_7': 607,
    'NDMC_8': 608,
    'NDMC_9': 609})
data['WARD_NO'] = data['WARD_NO'].astype(int)
mean_temp= data.groupby('WARD_NO')['LST 16may2020'].mean()
result = pd.DataFrame({'WARD_NO': mean_temp.index, 'mean_temp': mean_temp.values})
result.to_excel("C:/Users/gulsh/Downloads/ward_vs_mean_temp.xlsx", index=False)

In [27]:
import pandas as pd
data = pd.read_excel("C:/Users/gulsh/Downloads/landcover with area.xlsx")
data['WARD_NO'] = data['WARD_NO'].replace({'CANT_1': 501,
    'CANT_2': 502,
    'CANT_3': 503,
    'CANT_4': 504,
    'CANT_5': 505,
    'CANT_6': 506,
    'CANT_7': 507,
    'CANT_8': 508,
    'NDMC_1': 601,
    'NDMC_2': 602,
    'NDMC_3': 603,
    'NDMC_4': 604,
    'NDMC_5': 605,
    'NDMC_6': 606,
    'NDMC_7': 607,
    'NDMC_8': 608,
    'NDMC_9': 609})
data['WARD_NO'] = data['WARD_NO'].astype(int)
# Assuming the dataset is stored in a DataFrame called 'data'
filtered_data = data[data['landcover'] == 7]

ward_area = filtered_data.groupby('WARD_NO')['Area'].sum()
total_area = data.groupby('WARD_NO')['Area'].sum()

percentage_area = (ward_area / total_area) * 100

result = pd.DataFrame({'WARD_NO': percentage_area.index, 'landcover_percentage': percentage_area.values})
result
# Print the result
result.to_excel("C:/Users/gulsh/Downloads/ward_vs_landcover7percentage.xlsx", index=False)

In [30]:
import pandas as pd
data = pd.read_excel("C:/Users/gulsh/Downloads/ward_income.xlsx")
data['WARD_NO'] = data['WARD_NO'].replace({'CANT_1': 501,
    'CANT_2': 502,
    'CANT_3': 503,
    'CANT_4': 504,
    'CANT_5': 505,
    'CANT_6': 506,
    'CANT_7': 507,
    'CANT_8': 508,
    'NDMC_1': 601,
    'NDMC_2': 602,
    'NDMC_3': 603,
    'NDMC_4': 604,
    'NDMC_5': 605,
    'NDMC_6': 606,
    'NDMC_7': 607,
    'NDMC_8': 608,
    'NDMC_9': 609})
data['WARD_NO'] = data['WARD_NO'].astype(int)
data['income level'].fillna(1, inplace=True)
ndata= data[['WARD_NO','P_D2020','income level']]
ndata.to_excel("C:/Users/gulsh/Downloads/ward_vs_income&populationdensity.xlsx", index=False)

In [35]:
ward_vs_incomepopulationdensity= pd.read_excel("C:/Users/gulsh/Downloads/ward_vs_income&populationdensity.xlsx")
ward_vs_landcover7percentage= pd.read_excel("C:/Users/gulsh/Downloads/ward_vs_landcover7percentage.xlsx")
ward_vs_mean_temp= pd.read_excel("C:/Users/gulsh/Downloads/ward_vs_mean_temp.xlsx")
ward_vs_residential_area= pd.read_excel("C:/Users/gulsh/Downloads/ward_vs_residential_area.xlsx")


from functools import reduce
df=reduce(lambda x,y: pd.merge(x,y, on='WARD_NO', how='outer'), [ward_vs_incomepopulationdensity,ward_vs_landcover7percentage, ward_vs_mean_temp,ward_vs_residential_area])
df.fillna(0, inplace=True)
df.to_excel("C:/Users/gulsh/Downloads/df.xlsx", index= False)

In [38]:

import pandas as pd
from scipy import stats

# Assuming the dataset is stored in a DataFrame called 'data' and the column name is 'column_name'
data = pd.read_excel("C:/Users/gulsh/Downloads/df.xlsx")
column_names = ['P_D2020', 'income level', 'landcover_percentage', 'mean_temp', 'Residential_area_percentage']

for column in column_names:
    data[column + '_zscore'] = stats.zscore(data[column])

data.to_excel("C:/Users/gulsh/Downloads/df_zscore.xlsx", index= False)

In [40]:
import pandas as pd
import numpy as np
data = pd.read_excel("C:/Users/gulsh/Downloads/df_zscore.xlsx")
# Assuming the z-scores are stored in columns 'column1_zscore', 'column2_zscore', etc.
zscore_columns = ['P_D2020_zscore', 'income level_zscore', 'landcover_percentage_zscore', 'mean_temp_zscore', 'Residential_area_percentage_zscore']

# Calculate HVI component scores for each z-score column
for zscore_column in zscore_columns:
    data[zscore_column.replace('_zscore', '_hvi')] = np.where(data[zscore_column] <= -2, 1,
                                                             np.where(data[zscore_column] <= -1, 2,
                                                                      np.where(data[zscore_column] <= 0, 3,
                                                                               np.where(data[zscore_column] <= 1, 4,
                                                                                        np.where(data[zscore_column] <= 2, 5, 6)))))

# Print the updated DataFrame
data.to_excel("C:/Users/gulsh/Downloads/df_zscore_hvi.xlsx", index=False)